### ISSUE TITLE
Fatal error in taxonomy-custom_cat.php file

### ISSUE THREAD

**Issue by alisiddique** [eddiemachado/bones#600]
Fatal error: Call to undefined function bones_get_the_author_posts_link() in H:\SERVER\XAMP\htdocs\WP-THEME\wp-content\themes\bones\taxonomy-custom_cat.php on line 33

Please need help

**Comment by shubhra14** [comment]
I am getting the same error. Did not change anything..

**Comment by ivanildodias** [comment]
This function is not configured. This is only called in file `taxonomy-custom_cat.php`.

![issue-600_bones](https://cloud.githubusercontent.com/assets/10048508/8910435/158295f0-345d-11e5-95b4-146b06cf1f0e.JPG)

**Comment by AdsonCicilioti** [comment]
@ivanildodias está em todas!! uhasuhasuh xD

**Comment by ivanildodias** [comment]
@AdsonCicilioti...
Sempre tentando ajudar! :D
