### ISSUE TITLE
Incorrect link to apple-touch-icon

### ISSUE THREAD

**Issue by mavix** [eddiemachado/bones#721]
header.php says: 

`<link rel="apple-touch-icon" href="<?php echo get_template_directory_uri(); ?>/library/images/apple-icon-touch.png">`

Icon is named:

`apple-touch.icon.png` in library/images/

Small fix and easily fixed on my end :)

Cheers and thanks for a fabulous theme!

**Comment by KostasNi** [comment]
I didn't see a pull request to fix this issue, so I submitted one.
