### ISSUE TITLE
Extra space before #inner-content

### ISSUE THREAD

**Issue by embryomedia** [eddiemachado/bones#734]
I've added an extra div before #inner-content and for some reason I'm getting extra space (about 5px or so) at the bottom of the added div. I can't track down any css issues that could be causing it. Any ideas?

See these pages for example:
http://embryomedia.ca/atptest/contact/
http://embryomedia.ca/atptest/

Any assistance you could provide would be greatly appreciated.

Thanks in advance!
Celeste

**Comment by scottstreit** [comment]
This isn't an issue with bones, it's just a css problem. 

If you set the image and iframe to ```display: block``` this will remove the extra space at the bottom.

**Comment by embryomedia** [comment]
My bad! Thanks for sorting that out for me :)
