### ISSUE TITLE
404.php not working

### ISSUE THREAD

**Issue by digitalvaldosta** [eddiemachado/bones#746]
I downloaded a recent copy of bones and have been working on a theme (locally) for a client. However I started to work on 404.php and it only shows the following generic message:

<blockquote>
<h1>Not Found</h1>
<p>The requested URL /bowden/x was not found on this server.</p>
<hr>
<address>Apache/2.2.22 (Ubuntu) Server at localhost Port 80</address>
</blockquote>

I've attempted creating a new 404.php and can't seem to figure out what is wrong. I have looked through the other issues and didn't see anyone else having this issue.

I am getting to this error by typing a random word or letter after the home address (<em>i.e.</em>, localhost/bones/x)

Any help would be appreciated. 

<b><em>T.I.A.</em></b>

**Comment by Tanmccuin** [comment]
I'm pretty sure this is related to your localhost config and not bones specifically - have you tried another theme to confirm?

**Comment by digitalvaldosta** [comment]
It had more to do with how I was typing in the address on my localhost. But yes that was also part of why it wasn't working. I now have the 1.0 version of the theme online and the 404.php is working. 

Locally I have to type the address like: <a href="http://localhost/bowden/?p=1000" target="_blank">localhost/bowden/?p=1000</a>. But once it was uploaded it doesn't matter. If you type a URL that doesn't exist I get the 404 that I created. Thanks for the help.
