### ISSUE TITLE
Where is .cf ?

### ISSUE THREAD

**Issue by Alysko** [eddiemachado/bones#755]
Hi,

On style.scss, line 762 (for now) we have `@extend .cf` but I don't find .cf anywhere. Then compass watch says `Use "@extend .cf !optional" if the extend should be able to fail.`

**Comment by Hlsgs** [comment]
its in partials/normalize.scss
btw, forget compass and go for grunt or gulp. you will never go back.

**Comment by Alysko** [comment]
Oh ! Thanks, compass don't see it; I don't know why... I agree for grunt/gulp (or brunch ?) but I'm tired to change all my tools every year because the new ones are more awesome than the previous :(
