### ISSUE TITLE
Theme without comments?

### ISSUE THREAD

**Issue by webdevbrian** [eddiemachado/bones#776]
Hi all,

Been a user of the bones theme for many years. Have another client project we're working on and figured I'd ask my everlasting question each time we use it --

Can we get a version without all of the comments scattered throughout the files? E.g. CSS, template files, everywhere. We constantly delete them and the processes is always mundane at best.

Thanks.

**Comment by Hlsgs** [comment]
Minimizing the css/js files is best practice. That automatically removes all the comments if you so choose. Your point is moot.

**Comment by webdevbrian** [comment]
Not if we use the stylesheets before minimizing, which we do. It'd be great to have it all removed, the two step needed of minimizing, then un-minimizing is a pain at best.

So - your reply is not the answer

**Comment by scottstreit** [comment]
If you really want to have a copy of bones without comments I suggest you fork it and maintain it yourself exactly the way you want it.

**Comment by webdevbrian** [comment]
What? There's comments scattered everywhere in virtually every file (not just the CSS file) -- I think everyone knows this, though.

We manually scrape each file and remove hundreds of lines of comments -- mind you, they're not typical code comments, as they often go into an overelaboration on what snippet it's in regards too, and almost (while funny and "fun") always have some sort of joke tied to the comment.

There's just too much bloat, and it's in direct relation to the sheer amount of comments which are scattered throughout the theme files which is staggering at the very least.

**Comment by StormersFan** [comment]
I must say that I appreciate the comments and find them very useful. Minimizing and forking sound like reasonable suggestions and I wonder if there are any other ideas for preparing / optimizing files for a production environment.

**Comment by alexgarces** [comment]
I learned a lot thanks to these comments some time ago, so I would say that Bones must keep the comments for Wordpress beginners. I think this "educational approach" is one of its strengths.

I'm with @StormersFan, maybe I miss a production ready version, but it could be a different fork.

**Comment by Hlsgs** [comment]
if one sets up a grunt script to handle minimizing and other amazing(autoprefixing, concatenation etc) stuff automatically, the comments are no longer an issue as far as js and css go. one can even go as far as to even remove the php comments via a grunt task, thopugh i fail to see why one would bother..

**Comment by Hlsgs** [comment]
and if grunt/gulp is a little scary, you can always go with gui programs that do these things. if you're not using these sort of tools  in 2015 and still using plain old css.. well i dont mean to ofeend but you should get with the times :)

**Comment by webdevbrian** [comment]
It should be offered with all of the fluff, that's all it comes down to. I figured I'd mention it because the comments in almost all of the file is excessive.

No offense taken, we've been "with the times" for the 10 years being in business.

:)

**Comment by Hlsgs** [comment]
i think @eddiemachado is correct in not allowing scripts for these tools, as they are a highly personal choice(grunt/gulp/compass if you can bare the slow sass compiler). one is way better off learning how to make their own. and in case one is not so inclined, its very easy to use a gui like koala or prepros. give them a try and you'll never worry about comments, prefixes and whatnot. also, your time efficiency may improve by over 20%(mine did :) )
though, in the long run, i still recomend choosing between grunt and gulp. speeeeeeed! :)

**Comment by mndewitt** [comment]
I think the comments are essential, and they are one of the reasons I chose this theme and recommend it to other people.

If I was so personally bothered by them, I would write a PHP script to scan all the files and remove all comments via regex, except for style.css and any custom page templates (and any files where you'd like to preserve the comments).  You could continue to use the theme on new projects and simply run the script every time.  Better yet, you could integrate your whole workflow with WP-CLI and write a shell script to spin up a new WP instance, download the theme from github, then run your comment removal script with minimal overhead.

**Comment by PeterBeckley** [comment]
I think the front page of the project (http://themble.com/bones/) explains it all so well in two short phrases:
"Keep what you need, remove what you don't. It's totally up to you" and "Featuring the most detailed stylesheets evar, Bones takes pride in showing you exactly what selectors do what and gives them to you in a neat and easy to understand way." 

It's never been for people who want a naked style sheet, evar. That's what forks are for, and one of the most powerful features of GitHub!

**Comment by webdevbrian** [comment]
Development vs production folks, that's what this comes down too. I never said the comments were a bad thing, but it should be crazy easy to mix it in.

So many people have / are deploying sites with all of that fluff. I will go and say it will shrink the size of everything by 40-60% easily.

Convo is pretty much over, it isn't about fandom of bones, it's about offering two flavors. The comments are excessive if you like them or not.
