### ISSUE TITLE
Full Width Page

### ISSUE THREAD

**Issue by MazzyK** [eddiemachado/bones#777]
For the love of God please help me. I am a programmer, and have a good working knowledge of web development including SASS. I have recently got to grips with responsive design and grid layouts but I must be missing something (probably very stupid of me) because for the life of me I have not been able to create a full width template for Wordpress using bones (i.e. don't want white space on the sides along the length of my page). If there is anyone who can point me in the right direction I emplore you to do so. I have spent 4 days trying to find the solution to this and I just can't. What have I not got?

![layout](https://cloud.githubusercontent.com/assets/13525704/8913639/d0d2dfdc-34a2-11e5-87f9-6efeb0ab4a52.jpg)

**Comment by joshuaiz** [comment]
Look at the grid.scss file. You want to use d-all (and/or t-all + m-all) for your main content section (#main).

You'll also need to change the .wrap class (added to #inner-content) to be full width of your page so either pixel dimensions or most likely 100%.

**Comment by MazzyK** [comment]
Just to make sure I have understood you. I have this already does it match what you are suggesting?
----------------------------------
Excerpt from page.php
----------------------------------
<?php get_header(); ?>

			<div id="content">

				<div id="inner-content" class="wrap cf">

						<main id="main" class="m-all cf" role="main" itemscope itemprop="mainContentOfPage" itemtype="http://schema.org/Blog">
--------------------------------------------------------------------------------------------------------------------------
and then I have the following in my css:
.wrap {
	width: 100%;
}
-------------------------------------------------
If that's what you mean, I have that already. The outcome is that the space on the left of my screen goes away (yeah!) but I still have the gap on the right side of my screen along the edge of my sidebar (boo). Did I misunderstand what you suggested?

**Comment by joshuaiz** [comment]
You will have to adjust the width of #main and #sidebar to fit your page so maybe something like this:
     <main id="main" class="m-all t-2of3 d-2of3 cf" role="main" itemscope itemprop="mainContentOfPage" itemtype="http://schema.org/Blog">

And then in sidebar.php and maybe change the classes in that div: 

    <div id="sidebar1" class="sidebar m-all t-1of3 d-1of3 last-col cf" role="complementary">

So it just depends on what width(s) you want with your main section and sidebar — obviously they have to add up to 100% so maybe 2/3 and 1/3 or 3/5 and 2/5 or however you want to lay it out. The m-all only applies to mobile so you want to set your other widths explicitly for desktop (d-) and tablet (t-).

**Comment by MazzyK** [comment]
I am beginning to get it, but I am still not quite there sorry :(

So now my css has:
```
#main {
        width:80%;
}

#sidebar {
       width: 20%;
}
```
in page.php I have:
```
<main id="main" class="sidebar m-all t-2of3 d-2of3 last-col cf" role="main" itemscope itemprop="mainContentOfPage" itemtype="http://schema.org/Blog">
```
and in sidebar I have:

```
<div id="sidebar1" class="sidebar m-all t-1of3 d-1of3 last-col cf" role="complementary">
```
Where am I still going wrong?

**Comment by joshuaiz** [comment]
You either want to assign the widths in your css/scss OR use the grid. You are using both which will create unpredictable results. By using the classes t-2of3 d-2of3 you are assigning widths delineated in grid.scss - look at that file to see the widths of the grid classes. 

So either use the grid classes or remove them and assign percentage widths in your breakpoint scss files but do not use both.

**Comment by MazzyK** [comment]
Yes you are right I shouldn't be using both. I want to stick to the grid. I think I've got the right stuff in main and sidebar now. So that means there's something missing from my css still.

Earlier you said:

>You will have to adjust the width of #main and #sidebar to fit your page so maybe something like this:

>And then in sidebar.php and maybe change the classes in that div: 

Was there meant to be an example between the two sentences? I apologise, I am trying to find what I am missing.

**Comment by joshuaiz** [comment]
Yeah sorry it didn't get saved:

      <main id="main" class="m-all t-2of3 d-2of3 cf" role="main" itemscope     itemprop="mainContentOfPage" itemtype="http://schema.org/Blog">

But that looks close to what you have now. Remove the "last-col" from #main and add "first-col". That should do it.

**Comment by MazzyK** [comment]
It works!!!
Thank you for helping me out with my incorrect page.php and sidebar.php declarations. At one point I suspect they were correct but after the first two days of trying stuff I lost the ball with editing!

However, I also found the last thing which was preventing the page from showing up as it should. By default, when I installed the bones wordpress theme the file _1030up.scss contained the following declaration within
```
.wrap {
  width: 1040px;
}
```
I just double-checked and that's included when you download the theme from github. When you said before that I couldn't declare the width in two different places it clicked that the declaration in _1030up.scss should be changed to

```
.wrap {
  width: 100%;
}
```
This isn't exaclty a bug, but it should probably be changed. Is this something I can/should raise?

Thank you so very much for your help and your patience. You clarified the final grid layout elements I hadn't quite grasped. I hope I can be as useful for someone else on here one day :)

**Comment by joshuaiz** [comment]
That's not a bug or shouldn't be changed - some people want margins on either side and those should adjust relative to the overall width of the device so that should be there.

You did exactly the right thing by changing it to 100%.

**Comment by MazzyK** [comment]
Yes you are right again. Obviously I am having a "I'm the centre of the universe" moment, though after 4 days of desperation it's probably allowed.

Just in case anyone else ever refers to this thread I should point out that instead of first-col as per your earlier suggestion:

>But that looks close to what you have now. Remove the "last-col" from #main and add "first-col". That should do it.
I changed last-col to grid-col because _grid.scss already had the following declared:

```
@mixin grid-col {
  float: left;
  padding-right: 0.75em;

}
```
Again a big big thank you!

**Comment by MazzyK** [comment]
Closing this now as it is sovled.
