### ISSUE TITLE
jQuery question

### ISSUE THREAD

**Issue by drunaas** [eddiemachado/bones#778]
I am trying to make my sidebars fill up the space of the container. I have been researching this for quite a while and found the easiest thing would be to put this: $("#sidebar").height( $("#container").height() );
 into the scripts.js file, but it doesn't seem to work. Can anyone help me with this? I am fairly new to web design and am working on a site for a non-profit and the page in progress can be seen at stage.goldenknightdesign.com in case you need to see the code. Thanks in advance.

**Comment by joshuaiz** [comment]
You would need to target the sidebar class (.sidebar) or individual sidebars with id: #sidebar1, #sidebar2. Also instead of #container, you will want to target #main to get the height as that is the containing element of the sidebars - #container is everything within the body element.

Lastly, make sure your script is in the right place in scripts.js. It should be in this section:

      /*
     * Put all your regular jQuery in here.
     */
      jQuery(document).ready(function($) {

      /*
      * Let's fire off the gravatar function
      * You can remove this if you don't need it
      */
      loadGravatars();

      /* Your custom script should go here */

      }); /* end of as page load scripts */

You could also use this:

     var maxHeight = 0;

     $(".sidebar").each(function(){
       if ($(this).height() > maxHeight) { maxHeight = $(this).height(); }
     });

    $(".sidebar").height(maxHeight);

**Comment by drunaas** [comment]
Thanks for the fast response. I had the call in the right place, but needed to call the individual sidebars as you pointed out. The sidebars do go the full length now (when #main), but it has created another issue and now they push too far past the 3 posts. I tried having them fit to the size of a wrapper div I placed around the two sidebars and the article_wrapper, but this breaks the sidebar2 background color? If you could help me with this, it would be greatly appreciated.

**Comment by drunaas** [comment]
I messed around with it a little and it seems to be working o.k. now just using the #main? I don't know why it pushed them so far the first time, but it seems to look o.k. now? I may see if they will let me move the sponsors to the left sidebar to balance it out better? I would like to redo their sidebar images too, but I am running out of time on this project. Thanks again for your help.
