### ISSUE TITLE
Adding async to wp_register_script

### ISSUE THREAD

**Issue by shaunmac** [eddiemachado/bones#800]
So google page speed test tells me I need to "Eliminate render-blocking JavaScript and CSS in above-the-fold content". Which requires me to add ' async="async" ' to a few script tags. 

I found this post:
http://matthewhorne.me/add-defer-async-attributes-to-wordpress-scripts/
Which tells me I need to add a filter and replace strings with the new "async".

But when I add this fix to bones.php the script I'm trying to replace just dosn't load...

A simplified version of my bones.php 

```php
<?php
function bones_scripts_and_styles() {
    global $wp_styles;

    if(!is_admin()) {

       // normal bones register script
        wp_register_script( 'bones-modernizr', get_stylesheet_directory_uri() . '/library/js/libs/modernizr.custom.min.js', array(), '2.5.3', false );

    }//close !is_admin
    wp_enqueue_script( 'bones-modernizr' );
    
}//close bones_scripts_and_styles

//and here's the problem, when this is added it disappears the modernizr script from the head.
add_filter( 'script_loader_tag', function ( $tag, $handle ) {
    
    if ( 'bones-modernizr' !== $handle ) {
        return $tag;
    	return str_replace( ' src', ' async="async" src', $tag );
	}
    
}, 10, 2 );

?>
```
I'm obviously doing something wrong, anything you can help with would be greatly appreciated.

**Comment by maxmarkus** [comment]
You're returning $tag before your str_replace. first return wins.

        return $tag; // remove that one
        return str_replace( ' src', ' async="async" src', $tag );

**Comment by shaunmac** [comment]
@maxmarkus 
Thanks for getting back to me. That dose make sense now, but the problem I had was the modernizr script wasn't loading. But I found a fix after all, what I needed to do was this:

```
add_filter( 'script_loader_tag', function ( $tag, $handle ) {
    // I needed to remove the if statement  
    return str_replace( ' src', ' async="async" src', $tag );

}, 10, 2 ); 

```
Thanks again, this is by far the best base theme I've ever worked with. 

Should I send a pull request?

**Comment by maxmarkus** [comment]
Hi @shaunmac 
I think you've added some brackets for sake of readability, since having your code without the if {} brackets should also have worked. But I also prefer more expressive, than this one..
` if ( 'bones-modernizr' !== $handle ) 
      return $tag;
  return str_replace( ' src', ' async="async" src', $tag );
 `
I'm not into that project (have just used it once), but feel free to send pull requests as the maintainers will either merge or reject, I assume :)
