### ISSUE TITLE
Using Typekit with Bones starter theme

### ISSUE THREAD

**Issue by bibliofille** [eddiemachado/bones#805]
I'm using Bones as a starter theme for a site I'm developing and the clients wants to use two specific fonts from her Typekit account. 

I tried embedding the script in the header.php file. That didn't work. I also tried enqueueing the script in functions.php. That didn't work either. and now I'm stumped. 

I haven't added any other scripts or functions yet to my theme. Is there a default setting that I need to turn off or workaround in order to use these Typekit fonts? The client is using this kit on another site of hers. Could that be the issue? You can only use a "kit key" for one site?

**Comment by stevekirkby** [comment]
Hi
You're correct in adding the 2 lines of code Typekit gives to the header.php. You need to either create a new kit in Typekit with the fonts, or add the site to the existing kit (not forgetting to press Publish as I usually do). If you're developing locally the domain list in Typekit should include 127.0.0.1 and/or localhost. If you add both of these to the domain list, their order is important. The instructions in kit creation tool tips are pretty clear apart from that. I can provide examples of code tomorrow if needs be.
Steve

**Comment by joshuaiz** [comment]
Like @stevekirkby said above you have to explicitly add the domain(s) to your Kit. After you do that and Publish, then clear any caches you should be good to go. Chrome Dev Tools will show if anything is not loading and give you some indication as to why.

**Comment by bibliofille** [comment]
Aha! I am developing locally. Of course, that adds another dimension to the issue. :)  

My local domain for this build is: http://localhost:8888/pitchdev/. Would I still use 127.0.0.1?

I'll try this method first, and if that doesn't work, I'll try creating a new "kit" in Typekit. 

Thanks!

**Comment by joshuaiz** [comment]
Add the full domain just as you've typed it there - that is what gets sent out in the request.

**Comment by bibliofille** [comment]
So instead of using "//use.typekit.net/cbo2aac.js", I would use: "http://localhost:8888/pitchdev/use.typekit.net/cbo2aac.js"?

**Comment by joshuaiz** [comment]
You need to go to typekit.com > Kits > [your kit] > Kit Settings > Domains and add your domains there. 

localhost:8888/* should work after you (re) Publish and clear your local browser caches.

**Comment by joshuaiz** [comment]
The code you listed above is the embed code - that is wholly separate from the settings for your Kit - does that make sense?

**Comment by stevekirkby** [comment]
Add the full embed code to the header.php from the embed code link the top right of your kit, something like
<script src="https://use.typekit.net/yourscretcode.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>

**Comment by bibliofille** [comment]
Hmm, I added localhost:8888/pitchdev to domains in kit settings in Typekit, and cleared the cache, but it still didn't work. Perhaps making a new kit entirely would help.

**Comment by stevekirkby** [comment]
I'm just using localhost,127.0.0.1 for the domain. Are you using the full 2-line embed code found in the embed code link in the top right of your kit?

**Comment by bibliofille** [comment]
I'm using this: <script src="https://use.typekit.net/cbo2aac.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>

**Comment by stevekirkby** [comment]
Something like this...
    <script src="https://use.typekit.net/igr5wnx.js"></script>
    <script>try{Typekit.load({ async: true });}catch(e){}</script>

**Comment by joshuaiz** [comment]
It wouldn't hurt to create a new kit and get a new embed code. The domain settings can be kind of finicky. Try adding all of these:

localhost*
localhost:8888/*
localhost:8888/pitchdev/*

Make sure you (re) Publish your Kit. Also it can take a few (up to 30) minutes to propagate once you make changes so be patient. 

Some basic stuff:

- do you have weights enabled in your Kit?
- have you loaded the font into your Kit?
- have you added the CSS selectors into your CSS/SCSS files (important)? On typekit.com click on Kits > [your kit] > Using fonts in CSS. Make sure you have added that for the HTML elements you want to apply the fonts to.

**Comment by bibliofille** [comment]
Will do when I pick this back up tomorrow! Thanks for all your help, everyone!

**Comment by bibliofille** [comment]
I got it to work without even creating a new kit. I guess it took even longer than 30 minutes this time to propagate, but whatever, it works. Thanks again!
