### ISSUE TITLE
CSS positioning issue

### ISSUE THREAD

**Issue by bibliofille** [eddiemachado/bones#806]
I created a CSS text animation that I'm trying to implement into a site using Bones theme, but I can't quite get the positioning right. I have a feeling I'm just not putting it in the right place within Bones' structure and/or there's some other positioning setting further down the CSS that I need to adjust. 

Here's link to my animation in CodePen: http://codepen.io/bibliofille/pen/KVwxzz

I want to place it just above the footer on the home page, but right now, it just sits on top of the footer. I pasted the animation code on the homepage template after the loop, but before the </main> closing tag. 

![screenshot 2015-12-08 10 15 08](https://cloud.githubusercontent.com/assets/8399013/11691343/302d0b20-9e60-11e5-8013-1678bc302739.png)

Anyone have advice?

**Comment by dirad** [comment]
Hi B, this isnt really an issue with bones.
If you need CSS help, you should try stackoverflow.com.

Also, more of your code is needed to give you a good answer.
Generally though, you should put your animation markup in the footer.php file, probably..

**Comment by denisahac** [comment]
Hi @bibliofille I think you should enqueue your stylesheet properly in /library/bones.php. And be sure that no other stylesheet is overriding your CSS animation library. 

Also, for reference https://codex.wordpress.org/Function_Reference/wp_enqueue_style
