### ISSUE TITLE
Installing Retina.js in Bones theme 

### ISSUE THREAD

**Issue by bibliofille** [eddiemachado/bones#808]
I'm using Bones as a starter theme for a site I'm building, and I'm trying to install Retina.js to use hi DPI images when needed. 

I copied and pasted the Retina.js code into the Bones scripts.js file under where it says "Put all your regular jQuery in here." Is that the correct way to install JS into Bones? 

I tested one image by saving a higher res image, adding "@2x" to the file name. My laptop isn't retina capable, so I tried it on my iPhone 6, but the image resolution seems the same. How can I test it without a retina device? 

Here is the test site for reference: www.test.pitchdesignunion.com.

**Comment by joshuaiz** [comment]
You don't want to put the Retina.js code there as it is in it's own function. Place it after the last closing }); (see below). "Regular jQuery" is for your own custom bits; external plugins should be placed outside of that.

     /*
    * Put all your regular jQuery in here.
    */
     jQuery(document).ready(function($) {
     /*
       * Let's fire off the gravatar function
      * You can remove this if you don't need it
       */
     loadGravatars();
    }); /* end of as page load scripts */


     /* Place Retina.js or any jQuery plugin code below */


Once you've done that, try on your iPhone 6 or post back here and I can check on my retina MBP.

**Comment by bibliofille** [comment]
Ok, I copied and pasted the code as you suggested. Would you mind having a
look?

The top image on this page:
http://test.pitchdesignunion.com/project/threewalls/
should load the retina version.

Thanks!

On Wed, Jan 6, 2016 at 1:29 PM, Joshua Michaels <notifications@github.com>
wrote:

> You don't want to put the Retina.js code there as it is in it's own
> function. Place it after the last closing }); (see below). "Regular jQuery"
> is for your own custom bits; external plugins should be placed outside of
> that.
>
>  /*
> * Put all your regular jQuery in here.
> */
>  jQuery(document).ready(function($) {
>  /*
>    * Let's fire off the gravatar function
>   * You can remove this if you don't need it
>    */
>  loadGravatars();
> }); /* end of as page load scripts */
>
>
>  /* Place Retina.js or any jQuery plugin code below */
>
> Once you've done that, try on your iPhone 6 or post back here and I can
> check on my retina MBP.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eddiemachado/bones/issues/808#issuecomment-169431011>.
>



-- 
*Debbie Labedz*
Bibliofille Creative <http://www.bibliofille.com>

Twitter <https://twitter.com/bibliofilleblog> / Instagram
<http://instagram.com/bibliofille>

**Comment by joshuaiz** [comment]
The top image is @2x so that's working!

It's showing a 404 error for one @2x image: 

http://test.pitchdesignunion.com/wp-content/uploads/2015/12/2015-Margot-Harrrington-800px@2x.png

**Comment by bibliofille** [comment]
Thanks for checking, and thanks for the heads up!

On Wed, Jan 6, 2016 at 2:16 PM, Joshua Michaels <notifications@github.com>
wrote:

> The top image is @2x <https://github.com/2x> so that's working!
>
> It's showing a 404 error for one @2x <https://github.com/2x> image:
>
>
> http://test.pitchdesignunion.com/wp-content/uploads/2015/12/2015-Margot-Harrrington-800px@2x.png
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eddiemachado/bones/issues/808#issuecomment-169447632>.
>



-- 
*Debbie Labedz*
Bibliofille Creative <http://www.bibliofille.com>

Twitter <https://twitter.com/bibliofilleblog> / Instagram
<http://instagram.com/bibliofille>
