### ISSUE TITLE
Broken link in style.scss

### ISSUE THREAD

**Issue by philippepetitgenet** [eddiemachado/bones#809]
Hi, 

Line 15 you forget "www" .
Here is the rigth link : http://www.thesassway.com/advanced/modular-css-naming-conventions

;-)

**Comment by joshuaiz** [comment]
?? It works just fine without "www" as would any link.

**Comment by philippepetitgenet** [comment]
Rigth ! 
Problem was on my side visibly...apologies !

**Comment by Twintails** [comment]
@philippepetitgenet please close this issue if you have a chance.
