### ISSUE TITLE
adding Google Analytics tracking code

### ISSUE THREAD

**Issue by bibliofille** [eddiemachado/bones#815]
I tried adding my Google Analytics to my functions.php file, but I don't think it's working properly. When I log into my GA account, it hasn't registered any visits, though I know there should be some since I've visited the site on my phone, laptop, and desktop. 

Here's my code snippet (with the actual GA tracking code #s marked out):

`// Add Google Analytics tracking code 
<?php
add_action('wp_footer', 'add_googleanalytics');
function add_googleanalytics() { ?>
UA-xxxxxxxx-x ?>`

Any idea what the issue could be? Is there a better way to implement the code within the Bones theme?

**Comment by Hlsgs** [comment]
Better to put it directly in footer.php before the closing body tag.

**Comment by joshuaiz** [comment]
You need the full GA tracking code which should look something like this:

     <?php // drop Google Analytics Here ?>
     <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-XXXXXXXX-X', 'auto');
      ga('send', 'pageview');
     </script>
     <?php // end analytics ?>

Your tracking code may look different depending on your options. This is the newer async code.

I'd also just paste it in the header.php file between the <head></head> tags. The performance benefits of enqueueing or placing it in the footer are negligible.

Your code above does not include all the necessary bits from Google so it won't work. Also, you may have your login/ip address set to not register with Google Analytics and if so, none of your visits will show.

**Comment by bibliofille** [comment]
Thanks for the tip!

How can I find out whether or not my login/ip address is set up to register
with GA?

On Wednesday, March 16, 2016, Joshua Michaels <notifications@github.com>
wrote:

> You need the full GA tracking code which should look something like this:
>
>  <?php // drop Google Analytics Here ?>
>  <script>
>   (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
>   (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
>   m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
>   })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
>   ga('create', 'UA-XXXXXXXX-X', 'auto');
>   ga('send', 'pageview');
>  </script>
>  <?php // end analytics ?>
>
> Your tracking code may look different depending on your options. This is
> the newer async code.
>
> I'd also just paste it in the header.php file between the tags. The
> performance benefits of enqueueing or placing it in the footer are
> negligible.
>
> Your code above does not include all the necessary bits from Google so it
> won't work. Also, you may have your login/ip address set to not register
> with Google Analytics and if so, none of your visits will show.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/eddiemachado/bones/issues/815#issuecomment-197392373>
>


-- 
*Debbie Labedz*
Bibliofille Creative <http://www.bibliofille.com>

Twitter <https://twitter.com/bibliofilleblog> / Instagram
<http://instagram.com/bibliofille>

**Comment by joshuaiz** [comment]
In GA, go to Admin > [your property] > All Filters. There you can add your IP address to exclude it from tracking. You may or may not want to do this.

**Comment by bibliofille** [comment]
Ok, I dropped the GA code in the header.php file (see below for snippet), but I don't see it showing up when I use Chrome view source. Would it take a while to show up? 

`<?php // drop Google Analytics Here ?>
		 <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-xxxxxxx-x', 'auto');
  ga('send', 'pageview');

</script>

		<?php // end analytics ?>`

**Comment by bibliofille** [comment]
`<?php // drop Google Analytics Here ?>
		 <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-6253010-1', 'auto');
  ga('send', 'pageview');

</script>

		<?php // end analytics ?>`

**Comment by bibliofille** [comment]
Ok, I dropped the GA code into the header.php file. I don't see it, though, when I use Chrome view source. Would it take a while to show up? 

```
 <?php // drop Google Analytics Here ?>
	<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-xxxxxxx-x', 'auto');
  ga('send', 'pageview');

</script>
		<?php // end analytics ?>
```

**Comment by joshuaiz** [comment]
Are you sure you are looking in the `<head></head>` section of header.php. If it's there it should be there. You could try clearing any caches and your browser cache.

**Comment by bibliofille** [comment]
Here's a gist with everything I'm seeing in <head></head> of the homepage
when looking in view source, after clearing the browser cache.

https://gist.github.com/bibliofille/c6e2984287a8b3c05b0b

On Wed, Mar 16, 2016 at 11:55 AM, Joshua Michaels <notifications@github.com>
wrote:

> Are you sure you are looking in the <head></head> section of header.php.
> If it's there it should be there. You could try clearing any caches and
> your browser cache.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/eddiemachado/bones/issues/815#issuecomment-197422089>
>



-- 
*Debbie Labedz*
Bibliofille Creative <http://www.bibliofille.com>

Twitter <https://twitter.com/bibliofilleblog> / Instagram
<http://instagram.com/bibliofille>

**Comment by joshuaiz** [comment]
It doesn't make sense if you've added the code to header.php and uploaded it to your server, it should be there. Are you sure you are saving the header.php file? If you are working locally, are you sure you are copying the header.php file to the right place? Is it overwriting the current file?

There's no trick with this - you are simply adding the code snippet to the file. If it's there, it's there, if not, it's not. I really don't know what else to say.

**Comment by bibliofille** [comment]
Ok, I figured it out and now the tracking code shows up. Long story short, I had an issue connecting via FTP and the changes I made wouldn't save. It's always something, right?
