### ISSUE TITLE
Child Theme Support?

### ISSUE THREAD

**Issue by LoyalBen** [eddiemachado/bones#816]
First at all: Thank you for that great opportunities with bones! Great work I rally appreciate that!
The only thing I'm wondering is that **child themes do not work?** Why is that so and what for solutions do we have?

Best,

Benjamin

**Comment by Twintails** [comment]
I have built a couple child themes and seem to be working without issue. 
Can you determine what order you are calling your override styles? Are you registering the child theme styles and scripts with their own handles?

Trying to register the styles/scripts under the same handle that the parent registers will fail as they are already registered.

Try changing the handle for the child styles in the child/functions.php? or the child/library/bones.php

also verify the child theme has the "Template line" /*Docu-Block*/ in the child style.css?

Template: parent-theme-folder-name

This makes the child depend on the parent.
https://codex.wordpress.org/Child_Themes

hope this helps

**Comment by HowdyMcGee** [comment]
I can see how this is an issue. I believe the theme should be using `get_template_directory()` or `get_template_directory_uri()` in the place of `get_stylesheet_directory_uri()` in the `bones.php` file. 

Child Themes should be using `get_stylesheet_directory_uri()` so whenever you create a generic child theme, it's looking for library and the library styles / scripts **_in the child theme_** which I believe is an oversight. From The Codex:

[**get_stylesheet_directory_uri()**](https://codex.wordpress.org/Function_Reference/get_stylesheet_directory_uri) - In the event a child theme is being used, this function will return the child's theme directory URI.

[**get_template_directory_uri()**](https://developer.wordpress.org/reference/functions/get_template_directory_uri/) - In the case a child theme is being used, the absolute path to the parent theme directory will be returned.

So things like this:

`wp_register_script( 'bones-modernizr', get_stylesheet_directory_uri() . '/library/js/libs/modernizr.custom.min.js', array(), '2.5.3', false );`

Will be looking for this file in _the child theme_ directory when it needs to be changed to this instead:

`wp_register_script( 'bones-modernizr', get_template_directory_uri() . '/library/js/libs/modernizr.custom.min.js', array(), '2.5.3', false );`
