### ISSUE TITLE
adding MyFonts fonts to Bones theme 

### ISSUE THREAD

**Issue by bibliofille** [eddiemachado/bones#817]
I'm currently developing a site locally, and the client wants to use a couple fonts from MyFonts, and I'm having some issues figuring out how best to add these fonts. 

The MyFonts webfont kit came came with a folder with a "starthere.html" instruction file and a css stylesheet titled "True_To_Life.css". The instruction file said to add the stylesheet to the header.php file of the theme. 

I tried to add the stylesheet in the header.php file, but that did not work. The font loaded for one second, then went back to the sans-serif fallback. 

I know I should probably enqueue the script, but I'm not sure how to do that. Could anyone point me in the right direction?

**Comment by shaunmac** [comment]
You'll need to put your css file in the css folder.
Then you'll find a file named "bones.php" in the library directory.
In this file you'll need to register the style below the line testing if not admin: if(!is_admin()) { 

Paste this line under the start of the if statement:
`wp_register_style( 'bones-true-to-life', get_stylesheet_directory_uri() . '/library/css/True_To_Life.css', array(), '', 'all' );`

Then a little below that find this line: 
`wp_enqueue_style( 'bones-stylesheet' );`

And paste this below it: 
`wp_enqueue_style(' bones-true-to-life' );`

Now reload your page and it should be working : )

**Comment by bibliofille** [comment]
I followed your instructions, but still couldn't get it to work. I'm developing locally right now. Would that have anything to do with it? 

Thanks for the help so far!

**Comment by shaunmac** [comment]
Have you checked your console tab for 404?
Right click, inspect element, console tab.

**Comment by bibliofille** [comment]
Just checked and didn't see anything.

On Tue, Mar 22, 2016 at 10:36 PM, Shaun MacDougall <notifications@github.com
> wrote:

> Have you checked your console tab for 404?
> Right click, inspect element, console tab.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/eddiemachado/bones/issues/817#issuecomment-200151394>
>



-- 
*Debbie Labedz*
Bibliofille Creative <http://www.bibliofille.com>

Twitter <https://twitter.com/bibliofilleblog> / Instagram
<http://instagram.com/bibliofille>

**Comment by shaunmac** [comment]
Debbie can you put this up on a staging server? 
So I can have a look for myself. 

Might be something simple.

**Comment by bibliofille** [comment]
Sorry, I'm finally getting back to this site. It's now on the staging server: [.(http://www.test.truetolifetraining.com/)] Still having issues with the font. I'm sure it's something simple that I'm overlooking. 

Would you mind taking a look?

**Comment by bibliofille** [comment]
In looking at the test site [http://www.test.truetolifetraining.com/](url) there are several 404 errors for the font, so there must be something I'm doing wrong. I keep checking the file paths and I think they're correct now, but perhaps not.

**Comment by Twintails** [comment]
Though you registered the second stylesheet in order in the PHP code, it is still loading first. you can see that when inspecting the <head> on your test site. this is why you are seeing a Flash of Font Content then the styles are overridden by the bones theme. 

You can try enqueuing the second stylesheet with the $deps 
https://developer.wordpress.org/reference/functions/wp_enqueue_style/


specifically, you need the third parameter above in the wp_register_style to be array('bones-stylesheet')

`wp_register_style( 'bones-true-to-life', get_stylesheet_directory_uri() . '/library/css/True_To_Life.css', array('bones-stylesheet'), '', 'all' );`

Bear in mind, this should force the bones-stylesheet to be loaded first, but CSS specificity might still play a factor in how the font family styles are applied to the elements in question.

**Comment by Twintails** [comment]
As a friendly aside, you should consider uploading a much smaller file for your main image truetolife-header-home-2.png

1.82 MB is a lot to shove down and an end user. Especially over Mobile Phone connections. 
Try this fun tool out
https://whatdoesmysitecost.com

I suggest minimizing the size of your site to less than 500 KB but no more than 700KB and that is still a lot of data.
 
And use a JPEG at 70% or less quality. If you don't need transparency,  JPEG can be compressed to a smaller file than PNG. 

Apologies for the unsolicited advice :-)

**Comment by bibliofille** [comment]
Thanks for the help, Twintails! I managed to fix it by adjusting the file paths, which weren't correct. (Of course it was something simple. ) 

And thanks for the image advice as well. Yes, the header images are a beast, and need to be resized. On my to-do list. :)
