### ISSUE TITLE
Using Responsive-nav.js with Bones theme 

### ISSUE THREAD

**Issue by bibliofille** [eddiemachado/bones#819]
I'm running into issues implementing the Responsive Nav plugin into the Bones theme. 

I downloaded the plugin files and uploaded them to library/js in the theme directory. Then I added the following to the bones.php file: 

```
//register responsive nav plugin
		
wp_register_script( 'responsive-nav', get_stylesheet_directory_uri() . '/library/js/responsive-nav.js-master/responsive-nav.js', array(), '' );
```

and

`wp_enqueue_script( 'responsive-nav' );`

When I refreshed the page, I didn't see any changes, so I'm not sure I properly implemented the script. Did I miss a step?

**Comment by denisahac** [comment]
I'm pretty sure the script is loaded properly. And for you to make sure please check the script in the resources of the Developer's console.

And if this is the [JS plugin](http://responsive-nav.com/) you're talking about, then please follow the instructions according to the site.

I think you missed this line of code `responsiveNav(".nav-collapse");` in your custom script.

**Comment by bibliofille** [comment]
Sorry, just getting back to this! You're right, the script is firing, but t he collapsing isn't working. 

Where would I put the `responsiveNav(".nav-collapse");`?

**Comment by denisahac** [comment]
Put that line of code inside your custom JS file.

**Comment by bibliofille** [comment]
Could I put this directly into footer.php, or would it be better to put it in scripts.php under the section 
_Put all your regular jQuery in here._?

**Comment by denisahac** [comment]
It would be much better to put it in a your separate javascript file. Whatever works best for you!
