### ISSUE TITLE
Comments not appearing on post

### ISSUE THREAD

**Issue by bryns1** [eddiemachado/bones#826]
Not sure if I'm just making a stupid mistake... But comments section isn't appearing on blog posts. 
![screen shot 2016-04-19 at 8 37 55 pm](https://cloud.githubusercontent.com/assets/15933846/14637480/d855af60-0674-11e6-80f3-619b9266f49c.png)
![screen shot 2016-04-19 at 9 23 14 pm](https://cloud.githubusercontent.com/assets/15933846/14637516/1e69dda0-0675-11e6-8a30-e0a36e274281.png)

Comments aren't appearing on blog posts or anything. No php errors. Haven't modified any of original php files. De-activated all plugins and still not working. Very confused. Any help would be greatly appreciated

Running locally on Vagrant with VVV and latest WP install with multisite enabled.

**Comment by denisahac** [comment]
If you take a look at the [default post format](https://github.com/eddiemachado/bones/blob/master/post-formats/format.php)  you'll see the comment block is disabled by default on line number 70. The same goes to other post formats.

Hope that helps.

**Comment by bryns1** [comment]
Thank you @denisahac that worked
