### ISSUE TITLE
Hooks removing $ver in enqueues

### ISSUE THREAD

**Issue by jonnymaceachern** [eddiemachado/bones#828]
**(I'm working with an older version of `bones` and this doesn't seem to exist in the latest release)**

---

I noticed that my version number was being stripped in my `wp_enqueue_script` and `wp_enqueue_style`. After a bit of peaking around, I ended up finding the culprits:

    add_filter( 'style_loader_src', 'bones_remove_wp_ver_css_js', 9999 );
    add_filter( 'script_loader_src', 'bones_remove_wp_ver_css_js', 9999 );

I wanted to double check that they didn't serve an alternative purpose that will break when removed.

**Comment by Twintails** [comment]
please see Pull Request: --> hasn't been merged yet.
"Only remove ver from src if wp version #821"
https://github.com/eddiemachado/bones/pull/821

**Comment by Twintails** [comment]
The original Bones code strips out all versions from styles and scripts src strings. 

You can optionally remove the filters, but WordPress adds the current WP Core version number to the end of included styles and scripts, if they are not registered/enqueued with a version. 

This can lead hackers to knowing the version of WP you are running so they can target you with known attacks for those versions.  It's a remove at your own risk, sort of thing.

The PR code change removes version numbers only if the version matches current WP Core. Not 100% ideal if your script or style happens to match the Core Version naturally. However, a bit of an improvement over the method of removing all. 

Ideally the code could strip out WP Core Versions then check if the registration or enqueue contains the version string, and include it back, but thats seems somewhat of an "undo to do something again" and redundant.

**Comment by jonnymaceachern** [comment]
Perfect, thanks @Twintails
