### ISSUE TITLE
Using Masonry on Blog index with Bones theme 

### ISSUE THREAD

**Issue by bibliofille** [eddiemachado/bones#829]
I'm trying to use WordPress' built-in Masonry.js on a blog index page, and I've been following this tutorial: [http://www.wpbeginner.com/wp-themes/how-to-use-masonry-to-add-pinterest-style-post-grid-in-wordpress/](url)

I'm getting stuck on Step 2: Create Masonry Loop. The tutorial instructed me to create a template part called "content-masonry.php" and to implement that in the template. 

I created this file, but I'm not sure how to integrate it into the loop on blog.php. I only want the masonry to show up on the blog index page, not single posts.

**Comment by IngolfLarfeld** [comment]
Hi, I dont know if you still have the problem, but I dont created this file.
You have to create a container with the id="ms-container" around the loop and the post_class must be class="ms-item".

Here the part of my index.php:

<div id="content">

				<div id="inner-content" class="wrap cf">

					<?php if ( is_active_sidebar( 'sidebar_head' ) ) : ?>
						<div id="sidebar-header">
							<?php dynamic_sidebar( 'sidebar_head' ); ?>
						</div>
					<?php endif; ?>

										<?php get_sidebar(); ?>

						<main id="main" class="m-all t-2of3 d-5of7 home last-col cf" role="main" itemscope itemprop="mainContentOfPage" itemtype="http://schema.org/Blog">



							<div id="ms-container">

							<?php if (have_posts()) : while (have_posts()) : the_post(); ?>

							<article id="post-<?php the_ID(); ?>" <?php post_class( 'ms-item cf' ); ?> role="article">



And then in the footer a little piece of JavaScript:


		        jQuery(window).load(function() {

		      // MASSONRY Without jquery
		      var container = document.querySelector('#ms-container');
		      var msnry = new Masonry( container, {
		        itemSelector: '.ms-item',
		        columnWidth: '.ms-item',
		      });

		        });



That works for me.
