### ISSUE TITLE
Battle of the Blog (roll)

### ISSUE THREAD

**Issue by deyoglines** [eddiemachado/bones#834]
I've held out asking this, but after scouring the codex, many, many blogs and the issues here I'm stuck.

I've made a front-page.php template and have added a query after the static content to show 6 recent posts and it's working fine, I'd bee happy to add the link where I got the source code if interested. My head-knocker is when I choose a page to show posts for the entire roll with pagination I get nothing but one bit of excerpt from the most recent post, and the admin tool bar at the top is whited out. And somehow, it's pulling some html from my custom page template. I've looked for a missing <?php get_footer(); ?> or open div but nothing. Also I've downloaded a fresh zip and replaced the index.php and the other templates that I haven't edited and still get the same thing.

The weird thing is when I switch to the 2016 theme, it all works right. The query on the front page and the roll on a different page.

I'm local with MAMP and Codekit and NetBeans. I'd be happy to show any code or templates and any thoughts or links to possible answers would be lovely!

Thank you.

**Comment by joshuaiz** [comment]
Did you set the Posts page in Reading Settings? If you set that page in settings, it could use one of the default pages or index.php. Can you see what page template is that page using in Chrome Dev Tools? 

You may want to leave the Posts page in Reading settings at 'Select' and then create your own Posts page and specify your custom page template with a custom WP Query with pagination. I find that works better and I have more control.

**Comment by deyoglines** [comment]
Thanks @joshuaiz , I did set the in reading so I just set it back to select. It was using the default template page.php. Now as just a page it looks fine and the tool bar is back on top. 

"create your own Posts page and specify your custom page template with a custom WP Query with pagination."

Would be a new custom page template yes? And the new query should show the roll in the same way the loop would normally? Any thought on why assigning a blog page just isn't working like it should, I haven't really tweaked any functions as far as posts go but I did add an author bio box there which is working well, but could it be conflicting?

**Comment by joshuaiz** [comment]
If it is working how you want without the Posts page explicitly set then you can leave it as-is. I don't think the author bio box should affect anything.

You can always copy the whole loop from either: archive.php, index.php or tweak those to suit your needs to a new custom template. After doing that you could try setting the Posts page in the Reading settings.

I brought up the custom page template in case you wanted to say, show post excerpts (or a custom excerpt) for your posts or do any other kind of customization like show different elements for different categories and the like.

To do this, you can use the WP Query generator at http://generatewp.com to create a custom query loop, add that to your custom page template and then select that page template for your page (leaving the Posts page unspecified in Reading settings).

All that said, if you *do* specify the Posts page, if I remember correctly if you have a 'blog.php' template it will use that by default, or at least it should.

**Comment by deyoglines** [comment]
Thanks, this is great input. I just ran out of wall to bang my head on so I will try all the great suggestions in the AM. If it's cool I'll give a shout and let you know the outcome. If this needs to be closed now please do, or let me know to do so.

**Comment by deyoglines** [comment]
@joshuaiz , as usual I'm late to the party! http://generatewp.com is a great asset, thanks so much for this lead and all your help.
