### ISSUE TITLE
Migrating the Local Dev

### ISSUE THREAD

**Issue by deyoglines** [eddiemachado/bones#838]
I'll understand if I get vaporized for asking this, but is there a best or favorite way once local development is done to pack up Bones and migrate to a live host? I'm using Codekit/MAMP/(Netbeans for no particular reason) on my iMac OS 10.11.5. Just looking for opinions or advice, this is my first Bones try.

Thank you!

**Comment by Hlsgs** [comment]
Use the "WP Migrate DB" plugin to export the database content with the modified domain then just copy the whole WP install to the server and import the SQL. Don't forget to modify wp-config.php with the DB data from the host.

**Comment by deyoglines** [comment]
Thank you! I know this wasn't really an "Issue" so thanks for taking the time.
