### ISSUE TITLE
/library/css/style.css not being found

### ISSUE THREAD

**Issue by SRD75** [eddiemachado/bones#839]
Hi,

[This site](http://staging.taxrusaccounting.com.au/) cannot find

/wp-content/themes/bones/library/css/style.css

even though I see it on the server.

I don't understand why.

staging.taxrusaccounting.com.au lives in /public_html/staging, and 
/public_html/staging/wp-content/themes/bones/library/css/style.css exists.

I have the following plugins installed:

- Akismet
- Gravity Forms
- Wordfence Security
- WordPress Importer
- WP Migrate DB Pro

Help appreciated.

Regards,
Steve.

**Comment by badah** [comment]
It seems ok to me: http://staging.taxrusaccounting.com.au/wp-content/themes/bones-new/library/css/style.css

Could it be a cache issue?

**Comment by SRD75** [comment]
Yeah, you're right, I can see that now but not before.

However, the following rule is not being applied by the browser:

@media only screen and (min-width: 768px) {
    .nav li {
      float: left;
      position: relative;
    }
}

I can't see why.

**Comment by badah** [comment]
Ok, you have a typo in this CSS line:
`@media screen and (max-width: 600px} {`

It should be:
`@media screen and (max-width: 600px) {`

That should fix it.

**Comment by SRD75** [comment]
Oh damn, sorry to bother you, and thanks for the assistance. I appreciated it.
