### ISSUE TITLE
calling bones related posts function 

### ISSUE THREAD

**Issue by bibliofille** [eddiemachado/bones#844]
I'm trying to use the built-in related posts function, but I can't seem to get it to appear on the single posts template. 

I'd like the posts to appear above the comments template, so I added `<?php bones_related_posts();`?>` above the comments template call in the format.php file. I refreshed the page, but nothing appeared. 

Did I miss a step?

**Comment by JohnEcks** [comment]
Are you using custom post types?

If so, you need to add the `post_type` to the `$args` in order for related posts to show anything. I ran into this problem recently. I added `post_type` and `post_status` to make sure it would find the related posts for my custom type and those that were published.

If you're not using custom post types, not sure what the problem might be.
