### ISSUE TITLE
Sidebar top alignment 

### ISSUE THREAD

**Issue by simoneabc** [eddiemachado/bones#859]
Hello, I'd like to align the right sidebar with the content container as in the image attached. I tried to modify the base.scss o grid.scss paddings/margins of many elements but nothing seems to work… How I can resolve this question? Someone have the solution please?

![sidebar_alignment](https://cloud.githubusercontent.com/assets/24696755/21388136/3bfe712e-c77b-11e6-9b55-0dcf52556063.jpg)

**Comment by Hlsgs** [comment]
As specified in the comments, the best course of action is to roll your own grid. What Bones provides is more of an example than a full on production solution.

Easy way(do this if you are in a hurry): completly remove all grid classes from the templates(ex.: "m-all t-2of3 d-5of7") and manually set the width values for your elements)
Best way(you will thank yourself later): [http://susy.oddbird.net/](url)

**Comment by joshuaiz** [comment]
There is a margin set on .sidebar in 768up.scss:

     .sidebar {
          margin-top: 2.2em;
     }

Set that to "0" or remove it and you should be good to go.

**Comment by simoneabc** [comment]
Hi everyone, thank you for the answers, removing the top margin from sidebar on 768up.scss worked up perfectly. Thank you also for the Susy suggestion, I'll try to use it.
