### ISSUE TITLE
Bones Website Down

### ISSUE THREAD

**Issue by elebumm** [eddiemachado/bones#864]
Didn't know where else to put this so I thought I would here. The website to Bones is down.

**Comment by elebumm** [comment]
No response almost a month later. I went on the wayback machine and got this link here. 

https://web.archive.org/web/20161026005313/http://themble.com:80/bones/

**Comment by joeyjosay** [comment]
is this theme save to use? if it hasn't been updated in years?

**Comment by elebumm** [comment]
Yes it is @joeyjosay. It is still safe to use.

**Comment by joeyjosay** [comment]
Naive questions, could it ever be unsafe?

**Comment by Hlsgs** [comment]
Unsafe, no. Inadequate, yes, depending on your needs, what browsers you need to support and how WP develops further. But the latter is dependant on the needs of the project you want to start and shoudl be a question you should be asking on each and every one. When you're done with a project, no worries, there's nothing in Bones that can compromise security so you're all set.

**Comment by elebumm** [comment]
A bit of an aside here @Hlsgs but seeing that you are a contributor, is there any updates coming to bones? It's getting close to an entire year since a commit

**Comment by Hlsgs** [comment]
I've only contributed a couple of lines of CSS a while back. Only @eddiemachado knows the real state of the project.
But, TBH, if you roll with Bones' stated mantra and pick and choose what you need from it and then roll your own stuff like grids etc., I don't feel like there's much to add to the theme. And I still believe it to be a killer starting platform for people just getting into WP development as all the practices it "nags" in the comments are still on point.

**Comment by joeyjosay** [comment]
OK then. I have used it a few times so far, it saves a lot of work vs. underscores etc. I like the shiv, old ie campatible stuff, comments,  only thing missing is a mobile menu. i make all new page templates with ACF so its all work that needs doing anyway. Deleting the unused stuff is the worst of it but not too bad really. thanks again @Hlsgs

**Comment by Hlsgs** [comment]
@joeyjosay You should fork it and adapt it to your needs, so you don't need to deal with the mobile menu and other stuff that's common to most projects. I haven't been usign vanilla Bones for quite some time, but i do keep an eye out for changes i may want to include.

**Comment by joeyjosay** [comment]
i don't know what that is, fork

**Comment by Hlsgs** [comment]
It's a github thing. Basically you make your own copy and amster it how you wish. See here: https://help.github.com/articles/fork-a-repo/

However, if you're not into this stuff, just make a personalised copy on your rig that's got most of what you usually need and start from that, rather than from vanilla Bones. Just make sure to comment rather than remove code as you never know when you might need some snipped.

**Comment by joeyjosay** [comment]
ok, thanks, ill look in to that

**Comment by elebumm** [comment]
A new updated version of the website went up so I will close this issue! Thanks :)
