### ISSUE TITLE
get_terms wont listen to order => DESC

### ISSUE THREAD

**Issue by joeyjosay** [eddiemachado/bones#865]
Not sure if it is a theme problem or not, in an array I need this 
'order'      => 'DESC',
   'orderby'    => 'id',

It will not change the sort order when changed to ASC or DESC.
any thoughts?

**Comment by joeyjosay** [comment]
not sure what this means, string(273) "SELECT SQL_CALC_FOUND_ROWS wpbm_posts.ID FROM wpbm_posts WHERE 1=1 AND wpbm_posts.post_type = 'post' AND (wpbm_posts.post_status = 'publish' OR wpbm_posts.post_status = 'acf-disabled' OR wpbm_posts.post_status = 'private') ORDER BY wpbm_posts.post_date DESC LIMIT 0, 30"

**Comment by Hlsgs** [comment]
'orderby' => '**term_id**',

**Comment by joeyjosay** [comment]
thank tried that adn changed asc to desc no change alternating multiple times

**Comment by Hlsgs** [comment]
Can you share your full code?(that deals with the query)

**Comment by joeyjosay** [comment]
```
$args = array(
	'post_type'  =>  'specials',
	'taxonomy'   => 'places',
   'orderby' => 'date',
    'hide_empty' => false,
    'number'     => '0',

	'order'      => 'DESC', 
); 
             
$terms = get_terms($args);
foreach ( $terms as $term ) {
    $term_link = get_term_link( $term );
    if ( is_wp_error( $term_link ) ) {
        continue;
    }
    echo ' , <a  style="color:#000;"  target="_blank" href="' . esc_url( $term_link ) . '">' . $term->name . '</a>';
}
//$query = new WP_Query($args);
//var_dump($query->request);
```

**Comment by joeyjosay** [comment]
no matter what it returns the term with id of 4

**Comment by Hlsgs** [comment]
get_terms refers to taxonomies and does not accept a post type parameter. Also, "number" will limit you to one result, so drop it or don't do a foreach.

```
$args = array(
	'taxonomy'   => 'places',
      'orderby' => 'term_id',
      'hide_empty' => false,
      // 'number'     => '1',
	'order'      => 'DESC', 
); 
```
Anyway, this is not the proper place for this as it is completly unrelated to Bones.

**Comment by joeyjosay** [comment]
You don't think it has any interference from the theme? I thought maybe another bones user may have had an issue where they couldn't get this to work. I will see if a plugin is interfering with this. But i believe a foreach is needed as that is the only way to return the most recently created taxonomy term. Thanks for trying to help though. So even when I dont' use "number" it will not accept the ASC or DESC, thus wanting to find if it was theme related.

**Comment by Hlsgs** [comment]
It's 100% not theme related. If you are using WP >= 4.5.0, this should get and print you the latest added term in the "places" taxonomy:
```
$terms = get_terms( array(
	'taxonomy'   => 'places',
        'orderby' => 'term_id',
	'order'      => 'DESC',
        'hide_empty' => false,
        'number'     => 1,
) );

$latest_term = $terms[0];

print_r($latest_term);
```

**Comment by joeyjosay** [comment]
You're correct, thanks for all the help on the false alarm

**Comment by Hlsgs** [comment]
You're welcome! Close this if it's no longer relevant to you.
